config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
         
  validates :username, presence: true
         
  attachment :profile_image
  
  enum gender: { リーダー: 1, パートナー: 2 }
  
  enum prefecture: {
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
  }
  
  #性別による絞り込み
  scope :get_by_gender, ->(gender) {
  where(gender: gender)
  }
  #住所による絞り込み
  scope :get_by_prefecture, ->(prefecture) {
  where(prefecture: prefecture)
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_action :authenticate_user!, :only => [:create]
  
  # メッセージをcreate
  def create
    # form_forで送られてきたcontentを含む全てのメッセージの情報の:messageと:room_idのキーがちゃんと入っているか
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      # trueなら、trueだったら、メッセージを保存するためにMessage.createとし、
      # Messagesテーブルにuser_id、:content、room_idのパラメーターとして送られてきた値を許可
      # メッセージを送ったのは現在ログインしているユーザーなので、そのuser_idの情報をmerge
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :authenticate_user!
  
  # 新しくRoomとEntryを作成
  def create
    # Room_idを作成
    @room = Room.create
    # current_userをEntryに登録
    # current_userのEntry情報として、current_userのidと新しくできたroomのidを保存
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    # showのユーザーをEntryに登録
    # user#showで代入した@userの情報をidへ代入。そこに新しくできた:room_idをmergeして登録
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    # createと同時にチャットルームが開くようにredirect
    redirect_to "/rooms/#{@room.id}"
  end
  
  # 該当するチャットルームを表示
  def show
    @room = Room.find(params[:id])
    # Entriesテーブルに、current_userのidとそれにひもづいたチャットルームのidをwhereメソッドで探し、
    # そのレコードがあるか確認
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      # レコードがあるなら、Messageテーブルにそのチャットルームのidと紐づいたメッセージを表示させるため、
      # @messagesにアソシエーションを利用した@room.messagesという記述を代入
      @messages = @room.messages
      # 新しくメッセージを作成する場合は、メッセージのインスタンスを生成するために、
      # Message.newをし、@messageに代入
      @message = Message.new
      # rooms/show.html.erbでユーザーの名前などの情報を表示させるために、
      # @room.entriesを@entriesというインスタンス変数に入れ、Entriesテーブルのuser_idの情報を取得
      @entries = @room.entries
    else
      # レコードがなかったら前のページに戻るためにredirect_back
      redirect_back(fallback_location: root_path)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all.order(updated_at: :desc)
    # パラメータとして性別を受け取っている場合は絞って検索する
    if params[:gender].present?
      @users = @users.get_by_gender params[:gender]
    end
    # パラメータとして住所を受け取っている場合は絞って検索する
    if params[:prefecture].present?
      @users = @users.get_by_prefecture params[:prefecture]
    end
  end

  def show
    @user = User.find(params[:id])
    
    # roomがcreateされた時に、現在ログインしているユーザーと、
    # 「チャットへ」を押されたユーザーの両方をEntriesテーブルに記録する必要がある
    
    # 自分(current_user)が参加しているメッセージルーム情報を取得する
    @currentUserEntry=Entry.where(user_id: current_user.id)
    # 選択したユーザのメッセージルーム情報を取得する
    @userEntry=Entry.where(user_id: @user.id)
    
    # 自分(current_user)と選択したユーザ間に共通のメッセージルームが存在すればフラグを立てる
    
    # 選択したユーザーidと自分(current_user)のidが異なるとき
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          # 2つのブロック引数の中に同じRoom_idがあるかを確認
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      # もし2つのEntryに同じroom_idが見つからない場合新しくRoomとEntryを作る
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです！'
    end
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      sign_in(@user, bypass: true)
      redirect_to user_path(@user), notice: '更新しました！'
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  private
  
    def user_params
      params.require(:user).permit(:username, :email, :password, :profile_image, :gender, :prefecture, :profile)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-extend">
  <div class="container-fluid jumbotron-container">
    <h1>ダンスペアズ</h1>
    <p>ダンスペアズは、社交ダンスのリーダー・パートナーを見つけるためのアプリです。</p>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ダンスペアズ", root_url, id: "logo" %>
    </div>
    
    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <li><%= link_to "ペアを探す！", users_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン",   new_user_session_path %></li>
          <li><%= link_to "新規登録",   new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
    
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ダンスペアズ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if flash[:notice] %>
        <%= render 'layouts/flashes' %>
      <% end %>
      
      <% if flash[:alert] %>
        <%= render 'layouts/flashes' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/show.html.erb
<h1 class="text-center">メッセージ</h1>
<div class="jumbotron text-center">
  <div class="row">
    <h4>参加者</h4>
    <div class="card-deck">
      <% @entries.each do |e| %>
        <div class="col-sm-6">
          <div class="card bg-info">
            <%= attachment_image_tag e.user, :profile_image, fallback: "no-image.png", class: "card-img-top img-thumbnail" %>
            <div class="card-body">
              <h5 class="card-title"><strong><a href="/users/<%= e.user.id %>" class="card-title"><%= e.user.username%></a></strong></h5>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    
    <table class="table table-bordered width-90per">
      <tbody>
        <% if @messages.present? %>
          <% @messages.each do |m| %>
            <tr class="bg-success">
              <td style="width:75%">
                <strong class="white-space-pre-wrap"><%= m.content %></strong><br><small>(<%= m.created_at.strftime("%Y-%m-%d %H:%M") %>)</small>
              </td>
              <td style="width:25%">
                <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.username %></a></strong></small>
              </td>
            </tr>
          <% end %>
        <% else %>
          <h3 class="text-center">メッセージはまだありません</h3>
        <% end %>
      </tbody>
    </table>
    
    <%= form_for @message do |f| %>
      <%= f.text_area :content, :placeholder => "メッセージを入力して下さい", rows: 5, class: "form-control", id: "message-form" %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <br>
      <%= f.submit "投稿する", class: "btn btn-primary my-2", id: "submit-btn" %>
      <%= link_to "戻る", users_path, class: "btn btn-danger my-2", id: "back-btn" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">ユーザー編集</h1>
<section class="jumbotron text-center jumbotron-sign">
  <div class="container">
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @user.errors.full_messages.each do |m| %>
            <li><%= m %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @user, local: true do |f| %>
      <div class="field">
        <%= f.label :username, "ニックネーム" %><br />
        <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :email, "メールアドレス" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password, "パスワード" %><br />
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :profile_image, "プロフィール画像" %><br />
        <%= f.attachment_field :profile_image, autocomplete: "profile_image" %>
      </div>
      <div class="field">
        <%= f.label :gender, "性別" %><br />
        <%= f.select :gender, User.genders.keys, {prompt: '選択してください'}, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :prefecture, "住所" %><br />
        <%= f.select :prefecture, User.prefectures.keys, {prompt: '選択してください'}, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :profile, "プロフィール" %><br />
        <%= f.text_area :profile, autocomplete: "profile", class: "form-control", rows: 10 %>
      </div>
      <div class="actions">
        <%= f.submit "更新", class: "btn btn-lg btn-primary btn-block" %>
      </div>
      <div class="actions">
        <%= link_to "削除", user_path(@user), :method => :delete ,data: {confirm: "本当に削除しますか？"}, class: "btn btn-lg btn-danger btn-block" %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<h1 class="text-center">ユーザー一覧</h1>
<div class="text-center" id="search">
  <%= form_tag(users_path, method: "get") do %>
  <%= label_tag :gender, "性別" %>
  <%= select_tag :gender, options_for_select(User.genders), include_blank: true %>
  <%= label_tag :prefecture, "住所" %>
  <%= select_tag :prefecture, options_for_select(User.prefectures), include_blank: true %>
  <%= submit_tag "検索" %>
  <% end %>
</div>

<div class="jumbotron jumbotron-cover">
  <div class="row">
    <div class="card-deck">
      <% @users.each do |user| %>
        <div class="col-sm-6">
          <div class="card bg-success">
            <%= attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "card-img-top img-thumbnail" %>
            <div class="card-body">
              <h4 class="card-title">
                <%= link_to user_path(user) do %>
                  <h4 class="card-title"><%= user.username %></h4>
                <% end %>
              </h4>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= user.gender %></li>
            <li class="list-group-item"><%= user.prefecture %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center">ユーザー詳細</h1>
<div class="jumbotron jumbotron-cover text-center">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "card-img-top img-thumbnail" %>
        <div class="card-body">
          <h4 class="card-title">
            <h4 class="card-title"><%= @user.username %></h4>
          </h4>
        </div>
        <ul class="list-group list-group-flush text-left">
          <li class="list-group-item">性別：<%= @user.gender %></li>
          <li class="list-group-item">住所：<%= @user.prefecture %></li>
          <li class="list-group-item white-space-pre-wrap">プロフィール：<br><%= @user.profile %></li>
        </ul>
      </div>
      <% if @user.id == current_user.id %>
        <%= link_to "編集", edit_user_path(@user), class: "btn btn-primary my-2" %>
        <%= link_to "戻る", users_path, class: "btn btn-danger my-2" %>
      <% else %>
        <% if @isRoom == true %>
          <p><a href="/rooms/<%= @roomId %>" class="btn btn-primary my-2">チャットへ</a>
          <%= link_to "戻る", users_path, class: "btn btn-danger my-2" %>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value=> @user.id %>
            <% end %>
            <%= f.submit "チャットを始める！", class: "btn btn-primary my-2" %>
            <%= link_to "戻る", users_path, class: "btn btn-danger" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>